#!/usr/bin/env python3
"""Evaluation script for {PROJECT_NAME}.

Auto-generated by research-agent init. Modifies this file to fit your project.

Convention:
  - Loads a model checkpoint and runs N episodes with the CURRENT env.py
  - Reports completion_rate (mandatory), reward, and project-specific metrics
  - Output format matches research-agent metric_regex parsing

CLI:
  python .research-agent/evaluate.py <checkpoint_path> [--episodes N]
"""

import sys
import json
import argparse
import traceback
from pathlib import Path

# --- Project setup ---
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# --- Project-specific imports ---
# FILL: import your environment and model libraries
{IMPORT_ENV}
{IMPORT_MODEL}


def load_model(checkpoint_path: Path):
    """Load a model from checkpoint.

    FILL: implement model loading for your framework.
    Example for Stable-Baselines3:
        return TD3.load(str(checkpoint_path), device='auto')
    """
    {LOAD_MODEL}


def run_episode(env, model) -> dict:
    """Run a single episode and return metrics.

    FILL: implement episode execution for your environment.

    Must return:
        {
            "reward": float,           # total episode reward
            "steps": int,              # episode length
            "completed": bool,         # True if episode completed successfully
            ...                        # any project-specific metrics
        }
    """
    {RUN_EPISODE}


def evaluate(checkpoint_path: Path, n_episodes: int) -> dict:
    """Evaluate a model checkpoint for N episodes.

    Args:
        checkpoint_path: Path to the model checkpoint .zip file.
        n_episodes: Number of evaluation episodes.

    Returns:
        Dict with aggregated metrics.
    """
    import numpy as np

    if not checkpoint_path.exists():
        print(f"[ERROR] Checkpoint not found: {checkpoint_path}", flush=True)
        sys.exit(1)

    model = load_model(checkpoint_path)

    episode_rewards = []
    episode_lengths = []
    completed_count = 0
    # FILL: add project-specific metric collectors here
    {METRIC_COLLECTORS}

    for ep in range(n_episodes):
        # FILL: create environment for each episode
        {CREATE_EPISODE_ENV}

        ep_result = run_episode(env, model)

        episode_rewards.append(ep_result["reward"])
        episode_lengths.append(ep_result["steps"])
        if ep_result.get("completed", False):
            completed_count += 1
        # FILL: collect project-specific metrics
        {COLLECT_METRICS}

        env.close()

    completion_rate = completed_count / n_episodes
    mean_reward = float(np.mean(episode_rewards))
    std_reward = float(np.std(episode_rewards))

    result = {
        "completion_rate": completion_rate,
        "mean_reward": mean_reward,
        "std_reward": std_reward,
        "completed_episodes": completed_count,
        "total_episodes": n_episodes,
    }

    # FILL: add project-specific aggregated metrics
    # Example:
    # result["lateral_error"] = float(np.mean(lateral_errors))
    {AGGREGATE_METRICS}

    return result


def main():
    parser = argparse.ArgumentParser(description="Evaluate model checkpoint")
    parser.add_argument("checkpoint", type=str, help="Path to model checkpoint .zip")
    parser.add_argument("--episodes", type=int, default=30, help="Number of test episodes")
    args = parser.parse_args()

    checkpoint_path = Path(args.checkpoint)
    print(f"[EVAL] Testing model: {checkpoint_path}", flush=True)
    print(f"[EVAL] Episodes: {args.episodes}", flush=True)

    try:
        metrics = evaluate(checkpoint_path, args.episodes)
    except Exception as e:
        print(f"[ERROR] Evaluation failed: {e}", flush=True)
        traceback.print_exc()
        sys.exit(1)

    # Output JSON (for programmatic parsing)
    print("\n[METRICS]")
    print(json.dumps(metrics, indent=2))

    # Output parseable format (for research-agent metric_regex)
    # FILL: add all metrics that should be parsed by the optimizer
    print(f"\ncompletion_rate = {metrics['completion_rate']:.4f}")
    print(f"reward = {metrics['mean_reward']:.4f}")
    # FILL: add project-specific metrics
    # print(f"lateral_error = {metrics['lateral_error']:.4f}")
    {PRINT_METRICS}

    return metrics


if __name__ == "__main__":
    main()
