#!/usr/bin/env python3
"""Training script for {PROJECT_NAME}.

Auto-generated by research-agent init. Modifies this file to fit your project.

Convention:
  - RA_CHECKPOINT_DIR environment variable is set by the optimizer framework
  - Best model is saved to {RA_CHECKPOINT_DIR}/best_model.zip
  - Best model is determined by 10-episode average reward, checked on episode change

CLI:
  python .research-agent/train.py <seed> [--checkpoint-dir DIR] [--timesteps N]
"""

import os
import sys
import argparse
from pathlib import Path

# --- Project setup ---
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# --- Project-specific imports ---
# FILL: import your environment and model libraries
{IMPORT_ENV}
{IMPORT_MODEL}


class BestModelCallback:
    """Saves the best model by 10-episode average reward.

    Checks on every episode change (not every step).
    Reads episode rewards from the training environment.
    """

    def __init__(self, save_path: Path, last_n: int = 10, verbose: int = 1):
        self.save_path = save_path
        self.last_n = last_n
        self.verbose = verbose
        self.best_mean_reward = -float("inf")
        self.last_episode_count = 0

    def check(self, env):
        """Call this after each episode completes.

        Args:
            env: The unwrapped training environment.
        """
        epoch_r_list = getattr(env, "epoch_r_list", None)
        if epoch_r_list is None:
            return

        current_count = len(epoch_r_list)
        if current_count <= self.last_episode_count or current_count < self.last_n:
            return

        self.last_episode_count = current_count
        recent = epoch_r_list[-self.last_n:]
        mean_reward = float(sum(recent) / len(recent))

        if self.verbose:
            print(f"  [BestModel] ep={current_count} mean_reward={mean_reward:.2f} "
                  f"(best={self.best_mean_reward:.2f})")

        if mean_reward > self.best_mean_reward:
            self.best_mean_reward = mean_reward
            self.save_path.parent.mkdir(parents=True, exist_ok=True)
            # FILL: save your model here
            self._save_model()
            if self.verbose:
                print(f"  [BestModel] Saved new best model "
                      f"(ep {current_count}, reward={mean_reward:.2f})")

    def _save_model(self):
        """Save the current model to self.save_path.

        FILL: implement model saving for your framework.
        Example for Stable-Baselines3:
            self.model.save(str(self.save_path))
        """
        raise NotImplementedError("FILL: implement _save_model")


def train(seed: int, checkpoint_dir: Path, timesteps: int) -> dict:
    """Train the model and save the best checkpoint.

    Args:
        seed: Random seed for reproducibility.
        checkpoint_dir: Directory to save best_model.zip.
        timesteps: Total training timesteps.

    Returns:
        Dict with training metrics.
    """
    import time
    import numpy as np

    best_model_path = checkpoint_dir / "best_model.zip"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    # --- Create environment ---
    # FILL: create your training environment here
    {CREATE_ENV}

    # --- Create model ---
    # FILL: create your RL model here
    {CREATE_MODEL}

    # --- Setup best model callback ---
    callback = BestModelCallback(save_path=best_model_path, last_n=10, verbose=1)
    # FILL: set callback.model = model (so _save_model can access it)
    {SET_CALLBACK_MODEL}

    # --- Training loop ---
    t0 = time.time()
    # FILL: implement your training loop here
    # Example for Stable-Baselines3:
    #   model.learn(total_timesteps=timesteps, callback=...)
    #
    # For custom training loops, call callback.check(env) after each episode:
    #   while training:
    #       ... train one episode ...
    #       callback.check(unwrapped_env)
    {TRAIN_LOOP}
    elapsed = time.time() - t0

    # --- Cleanup ---
    # FILL: close environment, etc.
    {CLEANUP}

    return {
        "best_mean_reward": callback.best_mean_reward,
        "training_time_s": round(elapsed, 1),
        "timesteps": timesteps,
        "checkpoint": str(best_model_path),
    }


def main():
    parser = argparse.ArgumentParser(description="Train model for research-agent optimization")
    parser.add_argument("seed", type=int, help="Random seed")
    parser.add_argument("--checkpoint-dir", type=str, default=None,
                        help="Directory to save best model checkpoint")
    parser.add_argument("--timesteps", type=int, default={DEFAULT_TIMESTEPS},
                        help="Total training timesteps")
    args = parser.parse_args()

    # Determine checkpoint directory
    checkpoint_dir = None
    if args.checkpoint_dir:
        checkpoint_dir = Path(args.checkpoint_dir)
    elif os.environ.get("RA_CHECKPOINT_DIR"):
        checkpoint_dir = Path(os.environ["RA_CHECKPOINT_DIR"])
    else:
        checkpoint_dir = PROJECT_ROOT / "model" / "checkpoints"

    print(f"[TRAIN] seed={args.seed}, timesteps={args.timesteps}", flush=True)
    print(f"[TRAIN] checkpoint_dir={checkpoint_dir}", flush=True)

    metrics = train(args.seed, checkpoint_dir, args.timesteps)

    print(f"\n[TRAIN COMPLETE]", flush=True)
    print(f"  best_mean_reward: {metrics['best_mean_reward']:.2f}", flush=True)
    print(f"  checkpoint: {metrics['checkpoint']}", flush=True)


if __name__ == "__main__":
    main()
